15
:17:13Running build in Washington, D.C., USA (East) – iad115:17:13Build machine configuration: 2 cores, 8 GB15:17:13Cloning github.com/connorodea/FilmFusion (Branch: main, Commit: 6b70759)15:17:14Cloning completed: 425.000ms15:17:16Restored build cache from previous deployment (4Jvd1DjUhy8yyw8TpJqhnsX5dP78)15:17:17Running "vercel build"15:17:18Vercel CLI 46.0.215:17:18Detected `pnpm-lock.yaml\` 9 which may be generated by pnpm
@9.x
or
pnpm
@10.x15
:17:18Using pnpm
@10.x
based
on
project
creation
date15: 17
:18To use pnpm
@9.x
, manually opt in
using corepack
(https: //vercel.com/docs/deployments/configure-a-build#corepack)15:17:18Installing dependencies...15:17:19Lockfile is up to date, resolution step is skipped15:17:19Progress: resolved 1, reused 0, downloaded 0, added 015:17:19Packages: +1215:17:19++++++++++++15:17:19Progress: resolved 12, reused 0, downloaded 12, added 12, done15:17:1915:17:19dependencies:15:17:19+ next-intl 4.3.415:17:1915:17:19╭ Warning ─────────────────────────────────────────────────────────────────────╮15:17:19│ │15:17:19│ Ignored build scripts: @tailwindcss/oxide, sharp. │15:17:19│ Run "pnpm approve-builds" to pick which dependencies should be allowed │15:17:19│ to run scripts. │15:17:19│ │15:17:19╰──────────────────────────────────────────────────────────────────────────────╯15:17:1915:17:20Done in 1.4s using pnpm v10.14.015:17:20Detected Next.js version: 15.2.415:17:20Running "pnpm run build"15:17:2015:17:20> my-v0-project@0.1.0 build /vercel/path015:17:20> next build15:17:2015:17:21 ▲ Next.js 15.2.415:17:2115:17:21 Creating an optimized production build ...15:17:2115:17:21> Build error occurred15:17:21[Error: 15:17:21[next-intl] Could not locate request configuration module.15:17:2115:17:21This path is supported by default: ./(src/)i18n/request.{js,jsx,ts,tsx}15:17:2115:17:21Alternatively, you can specify a custom location in your Next.js config:15:17:2115:17:21const withNextIntl = createNextIntlPlugin(15:17:2115:17:21Alternatively, you can specify a custom location in your Next.js config:15:17:2115:17:21const withNextIntl = createNextIntlPlugin(15:17:21 './path/to/i18n/request.tsx'15:17:21);15:17:21]15:17:21 ELIFECYCLE  Command failed with exit code 1.15:17:21Error: Command "pnpm run build" exit\
